from libqtile.config import Screen
from libqtile import widget, bar
from settings.colors import Colors

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.TextBox(
                    text="",
                    padding_x=4,
                    fontsize=34,
                    background=Colors["oWhite"],
                    foreground=Colors["arch"],
                ),
                widget.TextBox(
                    text="\uE0B0",
                    fontsize=22,
                    padding=0,
                    background=Colors["odBlack"],
                    foreground=Colors["oWhite"],
                ),
                widget.GroupBox(
                    fontsize=23,
                    margin_y=3,
                    margin_x=0,
                    padding=7,
                    borderwidth=2,
                    active=Colors["white"],
                    inactive=Colors["fInactive"],
                    # rounded=False,
                    highlight_color=Colors["backCurrScr"],
                    highlight_method="line",
                    this_current_screen_border=Colors["arch"],  # line
                    this_screen_border=Colors["BlCoT"],
                    other_current_screen_border=Colors["WN"],
                    other_screen_border=Colors["BlCoT"],
                    foreground=Colors["white"],
                    background=Colors["background"],
                ),
                widget.TextBox(
                    text="\uE0B0",
                    fontsize=22,
                    padding=0,
                    foreground=Colors["odBlack"],
                    background="2D4263",
                ),
                widget.WindowName(
                    font="MesloLGS NF:style=Bold",
                    fontsize=16,
                    padding_x=1,
                    max_chars=65,
                    foreground=Colors["white"],
                    background="2D4263",
                ),
                widget.TextBox(
                    text="\uE0B2",
                    fontsize=22,
                    padding=0,
                    foreground=Colors["odBlack"],
                    background="2D4263",
                ),
                widget.Systray(),
                widget.Sep(
                    linewidth=0,
                    padding=8,
                    foreground=Colors["white"],
                    background=Colors["background"],
                ),
                widget.TextBox(
                    text="\uE0B2",
                    fontsize=22,
                    foreground="FEC260",
                    padding=0
                ),
                widget.KeyboardLayout(configured_keyboards=[
                    'latam', 'latam dvorak', 'us dvorak'],
                    background="FEC260",
                    foreground="141E61",
                    padding_x=1,
                ),
                widget.TextBox(
                    text="\uE0B2",
                    fontsize=22,
                    foreground="4A47A3",
                    background="FEC260",
                    padding=0
                ),
                widget.TextBox(
                    text="",
                    fontsize=24,
                    foreground=Colors["white"],
                    background="4A47A3",
                    padding=0
                ),
                widget.Volume(
                    foreground=Colors["white"],
                    background="4A47A3",
                    fontsize=15,
                    step=5,
                    channel='Master',
                ),
                widget.TextBox(
                    text="\uE0B2",
                    fontsize=22,
                    foreground="62A388",
                    background="4A47A3",
                    padding=0
                ),
                widget.TextBox(
                    text="",
                    fontsize=16,
                    foreground=Colors["white"],
                    background="62A388",
                    padding=0
                ),
                widget.Volume(
                    foreground=Colors["white"],
                    background="62A388",
                    fontsize=15,
                    step=5,
                    channel='Capture',
                ),
                widget.TextBox(
                    text="\uE0B2",
                    fontsize=22,
                    background="62A388",
                    foreground="00A8CC",
                    padding=0
                ),
                widget.Clock(
                    foreground=Colors["white"],
                    background="00A8CC",
                    fontsize=15,
                    format='%a %d %b %I:%M %p',
                ),
                widget.TextBox(
                    text="\uE0B2",
                    fontsize=22,
                    padding=0,
                    background="00A8CC",
                    foreground="AD1D45",
                ),
                widget.CurrentLayout(
                    font="mononoki Nerd Font:style=Bold",
                    fontsize=16,
                    foreground=Colors["white"],
                    background="AD1D45",
                    padding_x=1,
                ),
            ],
            24,
        ),
    ),
]
