require('settings')
require('pluggins')
require('colorschemes')
require('nvim-tree-config')
require('mappings')
require('lualine-config')
require('bufferline-config')
--require('lsp-config.language-servers')
